env:
  global:
  - TOOLS_DIR=$TRAVIS_BUILD_DIR/tools
  - PATH=$TOOLS_DIR/bin:$PATH
  - AWS_DEFAULT_REGION=eu-west-1
  - APP_VERSION=1.0
  - TERRAFORM_DEMO_BUCKET=demo-tfstates
language: bash
sudo: required
before_deploy:
- sudo pip install 'requests[security]' awscli
- "$TRAVIS_BUILD_DIR/tools/00_prerequisites.sh $TOOLS_DIR"
deploy:
- provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR/tools && ./01_deploy.sh
